
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 88
#define YY_END_OF_BUFFER 89
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[243] =
    {   0,
        0,    0,   89,   87,   84,   86,   85,   87,   87,   61,
       67,   70,   64,   51,   63,   53,   69,   52,   50,   68,
       62,   55,   58,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   59,   65,   73,   82,   56,    0,    0,
       81,   71,   72,   54,   83,    0,   52,    0,   48,   60,
       57,    0,   47,   47,   47,   47,    0,   47,   47,   47,
       47,   47,   47,    6,   47,   47,   47,   47,   47,   47,
       47,   16,   17,   47,   47,   47,   47,   22,   23,   47,
       47,   47,   47,   47,   47,   47,   47,   34,   47,   47,

       47,   47,   47,   49,    0,   66,    0,    0,    0,    1,
       47,    0,   47,   47,   47,   47,   47,    5,   47,   47,
        9,   47,   47,   12,   47,   47,   47,   47,   47,   19,
       20,   21,   47,   47,   47,   47,   47,   47,   47,   32,
       47,   47,   47,   47,   37,   47,   47,    0,   74,    0,
       75,   77,   80,   47,    0,   47,   47,    3,   42,   47,
       47,    8,   47,   27,   47,   47,   15,   47,   47,   47,
       47,   47,   47,   47,   47,   41,   47,   47,   44,   33,
       35,   47,   47,   39,    0,    0,    0,    2,    0,   26,
       47,    4,   47,   47,   47,   47,   45,   47,   18,   47,

       47,   47,   47,   47,   47,   47,   36,   38,   76,    0,
        0,   47,    7,   10,   47,   47,   47,   47,   46,   25,
       47,   47,   30,   31,   78,    0,   43,   47,   13,   47,
       40,   47,   47,   29,   79,   11,   14,   47,   47,   24,
       28,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    1,    1,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
       20,   21,    1,    1,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       31,   38,   39,   40,   41,   42,   43,   44,   45,   31,
       46,    1,   47,   48,    1,    1,   22,   23,   24,   25,

       49,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   31,   38,   39,   40,   41,   42,   43,   44,
       45,   31,   50,    1,    1,    1,    1,   51,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   52,   53,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   54,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[55] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    1,    1,    1,    1,
        1,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    1,    1,    1,    4,    1,
        1,    1,    1,    5
    } ;

static yyconst flex_int16_t yy_base[248] =
    {   0,
        0,    0,  328,  817,  817,  817,  817,  304,  312,  294,
      817,  293,  817,  817,  275,  278,  266,   41,  254,  817,
      248,  817,  227,   50,   53,   42,   44,   51,   73,   47,
       56,   83,   84,   72,   94,   99,  116,   87,  108,  124,
       28,  123,  133,  817,  817,  817,  817,  817,  234,  229,
      817,  817,  817,  817,  817,   44,  115,  138,  817,  817,
      817,  223,    0,  126,  146,  145,  174,  158,  146,  148,
      170,  165,  166,  170,  182,  187,  183,  195,  199,  200,
      205,  213,  218,  219,  231,  226,  232,  236,  244,  249,
      250,  262,  224,  265,  272,  272,  273,  274,  289,  293,

      303,  307,  310,  217,  304,   49,   65,   81,  205,  314,
      321,  155,  324,  320,  313,  330,  331,  316,  338,  348,
      349,  350,  351,  352,  359,  366,  367,  368,  383,  384,
      385,  386,  387,  402,  405,  416,  408,  419,  420,  421,
      422,  416,  428,  437,  439,  439,  447,  190,  178,  468,
      172,  169,  170,  452,  121,  457,  463,  467,  469,  474,
      481,  483,  489,  498,  489,  509,  498,  515,  520,  510,
      518,  525,  514,  535,  538,  539,  541,  546,  556,  567,
      570,  562,  560,  572,  139,  135,  121,  574,   82,  575,
      581,  590,  589,  584,  596,  600,  604,  596,  600,  615,

      616,  621,  635,  631,  650,  645,  654,  655,   99,   96,
       58,  653,  660,  659,  676,  654,  673,  676,  679,  681,
      682,  690,  684,  693,   85,   36,  701,  699,  703,  711,
      716,  719,  724,  731,    8,  732,  736,  746,  747,  748,
      751,  817,  800,  804,  807,  810,  811
    } ;

static yyconst flex_int16_t yy_def[248] =
    {   0,
      242,    1,  242,  242,  242,  242,  242,  242,  243,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  244,  244,   25,   25,   25,   25,   25,
       25,   28,   28,   25,   25,   25,   25,   25,   25,   25,
       28,   28,   28,  242,  242,  242,  242,  242,  243,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  245,   28,   28,   28,  242,   28,   25,   25,
       25,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   25,   25,   25,   28,   25,   25,   94,   94,

       94,   94,   94,  242,  242,  242,  242,  242,  246,   94,
       94,  242,   94,   28,   25,   25,   25,   25,   28,   25,
       25,   25,   25,   25,   94,   25,   25,   25,   25,   25,
       25,   25,   25,   94,   94,   94,   28,   25,   25,   25,
       25,   28,   25,   25,   25,   28,   28,  242,  242,  242,
      242,  242,  246,   28,  242,   28,   25,   25,   25,   25,
       25,   25,   25,   25,   94,   94,   94,   94,   94,   28,
       28,   28,   25,   25,   25,   25,   25,   94,   94,   94,
       94,   28,   25,   25,  242,  242,  242,   25,  242,   25,
       94,   94,   25,   28,   28,   28,   28,   25,   25,   25,

       25,   25,   25,   94,   94,   94,   94,   94,  242,  242,
      242,   28,   28,   94,   94,   25,   25,   25,   25,   25,
       25,   25,   25,   25,  242,  247,   25,   28,   28,   28,
       28,   28,   28,   28,  247,   28,   28,   25,   25,   25,
       25,    0,  242,  242,  242,  242,  242
    } ;

static yyconst flex_int16_t yy_nxt[872] =
    {   0,
        4,    5,    6,    7,    8,    5,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       31,   31,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   31,   31,   44,   45,   46,   28,   47,
        4,    4,    4,    4,   56,   62,   57,  105,   62,  106,
       64,  242,  100,   70,  106,   63,   58,   64,   63,   64,
       71,   64,   64,   73,  150,  107,   64,   72,   68,   74,
      151,   64,   81,   75,   65,   76,   64,   66,   69,   67,
       64,   64,   64,  108,   77,   64,  152,   64,   64,   64,

      225,   68,   78,   67,   64,   84,   67,   85,   79,   82,
      226,  225,   94,   80,  209,   64,   64,   83,   64,   64,
       64,   64,   64,   86,   64,   88,   64,   64,   56,   87,
       57,  185,  211,   95,   64,   94,   89,   92,   90,   91,
       58,   64,   64,   64,  101,  210,  187,   64,  107,   96,
      108,   64,   97,   93,  209,   64,   95,   64,   64,   98,
       64,  102,  103,   58,   64,   64,   64,   64,   99,   64,
      110,   64,   96,   64,  189,  242,   64,   64,   64,   64,
       64,  114,  111,   64,  152,  113,  115,  151,   64,   64,
       64,  116,   64,  149,   64,   64,   64,   64,   64,  117,

       64,   64,   64,  105,   64,   64,  155,  118,   64,   64,
       62,  121,  119,   64,   64,   64,   64,   64,   64,   64,
      120,   64,  122,   49,  112,   64,   64,  123,  109,   64,
       64,   64,   64,   64,  125,   49,  124,   64,   64,   64,
      104,  129,   64,   64,  126,   64,   61,   64,   64,   64,
       64,   64,   64,   64,  127,  130,   64,  128,  131,  136,
       64,   64,   64,   64,   64,   64,   64,   60,   64,   64,
       64,  132,   64,   59,   64,   64,   64,  133,   64,   64,
       55,   64,   64,   64,   64,  135,  137,   64,  138,  134,
       64,   54,   64,   64,   64,   53,   64,   64,  142,   64,

       64,  139,   52,   51,   64,   64,   64,   64,   64,   64,
       64,  140,   64,   64,   64,  141,   64,  148,   50,  149,
       64,  142,   64,   48,   64,  143,   64,  242,   64,   64,
       64,   64,  144,   64,  242,   64,  146,   64,  158,   64,
      145,   64,  154,   64,   64,   64,   64,   64,   64,  147,
       64,   64,  157,  156,   64,   64,   64,   64,  242,  242,
       64,  158,  242,   64,   64,   64,   64,  159,  242,  160,
       64,  242,  161,  162,   64,  163,  164,   64,   64,   64,
       64,   64,  166,   64,   64,   64,   64,   64,  242,  242,
      242,   64,   64,  169,  165,   64,  162,   64,  163,  164,

       64,  167,   64,   64,  242,  242,  242,  168,  170,   64,
       64,   64,  171,  242,   64,   64,  169,  242,   64,   64,
       64,   64,   64,   64,  242,   64,   64,  242,   64,  242,
      242,  170,   64,   64,   64,  171,  173,   64,  172,  174,
      176,   64,   64,  175,   64,  178,   64,   64,   64,  242,
      180,   64,   64,  181,  177,   64,   64,   64,  242,   64,
      242,  179,   64,   64,   64,  242,  182,   64,  178,   64,
       64,  183,   64,   64,   64,  184,  181,  242,  185,   64,
      186,   64,   64,  242,   64,   64,   64,   64,  191,   64,
       64,  190,   64,  187,   64,   64,  188,  242,   64,   64,

       64,  242,   64,  242,   64,  242,   64,  242,   64,   64,
      195,  191,   64,  192,   64,   64,   64,   64,   64,   64,
      193,   64,   64,   64,   64,   64,  194,  242,  242,   64,
       64,   64,   64,   64,   64,  242,   64,   64,   64,  202,
      242,   64,  199,   64,   64,   64,   64,  198,  196,   64,
       64,   64,   64,   64,  197,  200,   64,   64,  242,   64,
      203,   64,  202,   64,   64,  201,   64,  206,   64,   64,
       64,  242,  242,   64,   64,  204,   64,   64,  205,   64,
      242,  242,   64,  203,  242,  208,   64,   64,   64,   64,
       64,   64,   64,   64,  207,   64,   64,   64,  242,   64,

       64,  242,  212,   64,   64,   64,   64,   64,  208,   64,
       64,   64,  242,   64,   64,  242,   64,   64,  214,  242,
       64,  217,   64,   64,  213,   64,   64,   64,   64,  216,
       64,   64,   64,  215,   64,   64,   64,   64,   64,   64,
       64,   64,  242,   64,  217,  220,   64,   64,   64,  242,
       64,   64,  222,  242,   64,  219,   64,  218,  242,  221,
       64,  242,  242,   64,   64,  242,   64,   64,   64,   64,
       64,   64,  242,   64,  223,   64,   64,   64,   64,   64,
      228,   64,   64,   64,  224,   64,   64,  227,  242,  230,
       64,   64,   64,  242,   64,   64,   64,   64,   64,   64,

      229,   64,   64,   64,   64,  232,   64,   64,   64,   64,
      231,   64,   64,  242,   64,   64,   64,   64,   64,   64,
      242,   64,  233,  234,   64,   64,   64,   64,   64,   64,
       64,  236,   64,   64,  242,   64,   64,   64,   64,  242,
      242,   64,   64,   64,  242,  237,   64,  242,   64,   64,
       64,   64,  242,   64,   64,  242,   64,  238,   64,   64,
      242,  239,   64,   64,   64,   64,   64,   64,   64,  242,
       64,  240,  241,   64,   64,   64,   64,  242,  242,   64,
      242,   64,   64,   64,  242,  242,   64,  242,  242,  242,
      242,  242,  242,  242,  240,  241,   64,  242,  242,   64,

       49,   49,   49,   49,   49,   64,   64,   64,   64,   63,
       63,  153,  242,  153,  235,  235,    3,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242
    } ;

static yyconst flex_int16_t yy_chk[872] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   18,   24,   18,   56,   25,   56,
       41,  235,   41,   26,  106,   24,   18,   26,   25,   27,
       26,   41,   30,   27,  106,  107,   28,   26,   25,   27,
      107,   31,   30,   28,   24,   28,   28,   24,   25,  226,
       26,   31,   27,  108,   28,   30,  108,   34,   29,   28,

      225,   25,   29,   24,   31,   33,   25,   34,   29,   32,
      211,  210,   38,   29,  209,   32,   33,   32,   33,   35,
       34,   29,   38,   35,   36,   36,   32,   33,   57,   35,
       57,  187,  189,   39,   36,   38,   36,   37,   36,   36,
       57,   37,   35,   39,   42,  186,  187,   36,   58,   40,
       58,   37,   40,   37,  185,   42,   39,   42,   64,   40,
       64,   43,   43,   58,   37,   43,   42,   43,   40,   64,
       65,   69,   40,   70,  155,  153,   43,   66,   65,   66,
       65,   69,   66,   70,  152,   68,   70,  151,   66,   65,
       68,   71,   68,  149,   69,   71,   70,   72,   73,   72,

       73,   68,   74,  148,   74,   71,  112,   73,   72,   73,
      109,   76,   74,   74,   75,   77,   75,   77,   71,   76,
       75,   76,   77,  104,   67,   75,   77,   78,   62,   78,
       76,   79,   80,   79,   80,   50,   79,   81,   78,   81,
       49,   84,   79,   80,   81,   82,   23,   82,   81,   93,
       83,   84,   83,   84,   83,   85,   82,   83,   86,   93,
       86,   83,   84,   85,   87,   85,   87,   21,   88,   86,
       88,   87,   93,   19,   85,   87,   89,   90,   89,   88,
       17,   90,   91,   90,   91,   92,   94,   89,   94,   91,
       94,   16,   90,   91,   92,   15,   92,   95,   97,   98,

       94,   94,   12,   10,   96,   92,   96,   95,   97,   98,
       99,   95,   99,   94,  100,   96,  100,  105,    9,  105,
       95,   97,   98,    8,  101,   99,  101,    3,  102,  100,
      102,  103,  100,  103,    0,  110,  102,  110,  115,  101,
      101,  118,  111,  102,  111,  113,  103,  113,  115,  103,
      110,  118,  114,  113,  114,  116,  117,  111,    0,    0,
      113,  115,    0,  114,  118,  116,  117,  116,    0,  117,
      119,    0,  119,  120,  121,  122,  123,  124,  116,  117,
      125,  119,  125,  120,  121,  122,  123,  124,    0,    0,
        0,  126,  127,  128,  124,  125,  120,  121,  122,  123,

      124,  126,  127,  128,    0,    0,    0,  127,  129,  130,
      131,  132,  133,    0,  126,  127,  128,    0,  129,  130,
      131,  132,  133,  134,    0,  134,  135,    0,  135,    0,
        0,  129,  130,  131,  132,  133,  135,  136,  134,  136,
      137,  135,  137,  136,  138,  139,  140,  141,  142,    0,
      142,  137,  136,  143,  138,  139,  140,  141,    0,  142,
        0,  141,  144,  143,  145,    0,  144,  138,  139,  140,
      141,  146,  144,  146,  145,  147,  143,    0,  150,  147,
      150,  147,  146,    0,  154,  144,  154,  145,  157,  156,
      147,  156,  158,  150,  159,  154,  154,    0,  157,  160,

      156,    0,  158,    0,  159,    0,  161,    0,  162,  160,
      165,  157,  165,  160,  163,  158,  161,  159,  162,  167,
      161,  167,  160,  164,  163,  165,  163,    0,    0,  161,
      166,  162,  166,  164,  167,    0,  168,  163,  168,  173,
        0,  169,  170,  169,  170,  166,  164,  169,  166,  173,
      171,  168,  171,  170,  168,  171,  169,  172,    0,  172,
      174,  171,  173,  175,  176,  172,  177,  178,  172,  178,
      174,    0,    0,  175,  176,  175,  177,  179,  177,  179,
        0,    0,  178,  174,    0,  183,  175,  176,  180,  177,
      180,  181,  179,  181,  182,  183,  182,  184,    0,  188,

      190,    0,  191,  180,  191,  182,  181,  184,  183,  188,
      190,  192,    0,  192,  193,    0,  194,  191,  194,    0,
      184,  198,  188,  190,  193,  199,  192,  194,  195,  196,
      195,  198,  196,  195,  196,  199,  197,  193,  197,  195,
      200,  201,    0,  196,  198,  202,  202,  197,  199,    0,
      200,  201,  204,    0,  204,  201,  202,  200,    0,  203,
      203,    0,    0,  200,  201,    0,  206,  204,  206,  202,
      203,  205,    0,  205,  205,  207,  208,  207,  208,  216,
      214,  206,  214,  203,  206,  212,  205,  212,    0,  216,
      207,  208,  213,    0,  213,  214,  212,  215,  217,  215,

      215,  218,  216,  213,  219,  218,  220,  221,  217,  223,
      217,  218,  215,    0,  219,  222,  220,  221,  224,  223,
        0,  217,  221,  222,  218,  222,  227,  219,  224,  220,
      221,  228,  223,  228,    0,  229,  227,  229,  222,    0,
        0,  224,  228,  230,    0,  230,  229,    0,  231,  227,
      231,  232,    0,  232,  230,    0,  233,  232,  233,  231,
        0,  233,  232,  234,  236,  234,  236,  233,  237,    0,
      237,  238,  239,  240,  234,  236,  241,    0,    0,  237,
        0,  238,  239,  240,    0,    0,  241,    0,    0,    0,
        0,    0,    0,    0,  238,  239,  240,    0,    0,  241,

      243,  243,  243,  243,  243,  244,  244,  244,  244,  245,
      245,  246,    0,  246,  247,  247,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexical.l"
#line 2 "lexical.l"
/*
 * scan.l
 *
 * lex input file for pascal scanner
 *
 * extensions: two ways to spell "external" and "->" ok for "^".
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// 外部变量声明，yytext和yyin分别为字符指针和文件指针
// 这两个变量在lex提供的库中被定义，因此我们如果想要使用，必须添加extern声明
extern char *yytext;
extern FILE * yyin;

//"__config"
//"stdio.h"
//"_stdio.h"
//"sys/cdefs.h"
//"sys/_symbol_aliasing.h"
//"sys/_posix_availability.h"
//"Availability.h"
//"AvailabilityInternal.h"
//"_types.h"
//"sys/_types.h"
//"sys/cdefs.h"
//"machine/_types.h"
//"i386/_types.h"
//"sys/_pthread/_pthread_types.h"
//"sys/cdefs.h"
//"machine/_types.h"
//"sys/_types/_va_list.h"
//"machine/types.h"
//"i386/types.h"
//"i386/_types.h"
//"sys/cdefs.h"
//"sys/_types/_int8_t.h"
//"sys/_types/_int16_t.h"
//"sys/_types/_int32_t.h"
//"sys/_types/_int64_t.h"
//"sys/_types/_u_int8_t.h"
//"sys/_types/_u_int16_t.h"
//"sys/_types/_u_int32_t.h"
//"sys/_types/_u_int64_t.h"
//"sys/_types/_intptr_t.h"
//"machine/types.h"
//"sys/_types/_uintptr_t.h"
//"sys/_types/_size_t.h"
//"machine/_types.h"
//"sys/_types/_null.h"
//"sys/_types.h"
//"sys/stdio.h"
//"sys/cdefs.h"
//"Availability.h"
//
//"_ctermid.h"
//
//"sys/_types/_off_t.h"
//"sys/_types.h"
//"sys/_types/_ssize_t.h"
//"machine/types.h"

#define   AND      1
#define   ARRAY      2
#define   CASE      3
#define   CONST      4
#define   DIV      5
#define   DO      6
#define   DOWNTO      7
#define   ELSE      8
#define   END      9

#define   EXTERNAL      10
#define   FOR      11
#define   FORWARD      12
#define   FUNCTION      13
#define   GOTO      14
#define   IF      15
#define   IN      16
#define   LABEL      17
#define   MOD      18
#define   NIL      19
#define   NOT      20
#define   OF       21
#define   OR      22
#define   OTHERWISE      23
#define   PACKED      24
#define   PBEGIN      25
#define   PFILE      26
#define   PROCEDURE      27
#define   PROGRAM      28
#define   RECORD      29
#define   REPEAT      30
#define   SET      31
#define   THEN      32
#define   TO      33
#define   TYPE      34
#define   UNTIL      35
#define   VAR      36
#define   WHILE      37
#define   WITH      38
#define   IDENTIFIER      39

#define   ASSIGNMENT      40
#define   CHARACTER_STRING      41
#define   COLON      42
#define   COMMA      43
#define   DIGSEQ      44
#define   DOT      45
#define   DOTDOT      46
#define   EQUAL      47
#define   GE      48
#define   GT      49
#define   LBRAC      50
#define   LE      51
#define   LPAREN      52
#define   LT      53
#define   MINUS      54
#define   PLUS      56
#define   RBRAC      57
#define   REALNUMBER      58
#define   RPAREN      59
#define   SEMICOLON      60
#define   SLASH      61
#define   STAR      62
#define   STARSTAR      63
#define   UPARROW      64


#define   notEQUAL    65


#define   Enum	      67
#define   Sarray      68
#define   Sstring     69

#define   INTEGER     70
#define   REAL        71
#define   CHAR        72
#define   BOOLEAN     73
#define   TEXT        74
#define   INPUT       75
#define   OUTPUT      76

int line_no = 1;


#line 873 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 181 "lexical.l"


#line 1058 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 243 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 817 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 183 "lexical.l"
return(AND);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 184 "lexical.l"
return(ARRAY);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 185 "lexical.l"
return(CASE);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 186 "lexical.l"
return(CONST);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 187 "lexical.l"
return(DIV);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 188 "lexical.l"
return(DO);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 189 "lexical.l"
return(DOWNTO);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 190 "lexical.l"
return(ELSE);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 191 "lexical.l"
return(END);
	YY_BREAK
case 10:
#line 193 "lexical.l"
case 11:
YY_RULE_SETUP
#line 193 "lexical.l"
return(EXTERNAL);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 194 "lexical.l"
return(FOR);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 195 "lexical.l"
return(FORWARD);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 196 "lexical.l"
return(FUNCTION);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 197 "lexical.l"
return(GOTO);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 198 "lexical.l"
return(IF);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 199 "lexical.l"
return(IN);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 200 "lexical.l"
return(LABEL);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 201 "lexical.l"
return(MOD);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 202 "lexical.l"
return(NIL);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 203 "lexical.l"
return(NOT);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 204 "lexical.l"
return(OF); 
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 205 "lexical.l"
return(OR);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 206 "lexical.l"
return(OTHERWISE);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 207 "lexical.l"
return(PACKED);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 208 "lexical.l"
return(PBEGIN);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 209 "lexical.l"
return(PFILE);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 210 "lexical.l"
return(PROCEDURE);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 211 "lexical.l"
return(PROGRAM);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 212 "lexical.l"
return(RECORD);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 213 "lexical.l"
return(REPEAT);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 214 "lexical.l"
return(SET);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 215 "lexical.l"
return(THEN);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 216 "lexical.l"
return(TO);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 217 "lexical.l"
return(TYPE);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 218 "lexical.l"
return(UNTIL);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 219 "lexical.l"
return(VAR);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 220 "lexical.l"
return(WHILE);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 221 "lexical.l"
return(WITH);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 223 "lexical.l"
return(INTEGER);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 224 "lexical.l"
return(REAL);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 225 "lexical.l"
return(CHAR);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 226 "lexical.l"
return(BOOLEAN);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 227 "lexical.l"
return(TEXT);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 228 "lexical.l"
return(INPUT);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 229 "lexical.l"
return(OUTPUT);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 231 "lexical.l"
return(IDENTIFIER);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 233 "lexical.l"
return(ASSIGNMENT);
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 234 "lexical.l"
return(CHARACTER_STRING);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 235 "lexical.l"
return(COLON);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 236 "lexical.l"
return(COMMA);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 237 "lexical.l"
return(DIGSEQ);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 238 "lexical.l"
return(DOT);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 239 "lexical.l"
return(DOTDOT);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 240 "lexical.l"
return(EQUAL);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 241 "lexical.l"
return(notEQUAL);
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 242 "lexical.l"
return(GE);
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 243 "lexical.l"
return(GT);
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 244 "lexical.l"
return(LBRAC);
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 245 "lexical.l"
return(LE);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 246 "lexical.l"
return(LPAREN);
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 247 "lexical.l"
return(LT);
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 248 "lexical.l"
return(MINUS);
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 250 "lexical.l"
return(PLUS);
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 251 "lexical.l"
return(RBRAC);
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 252 "lexical.l"
return(REALNUMBER);
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 253 "lexical.l"
return(RPAREN);
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 254 "lexical.l"
return(SEMICOLON);
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 255 "lexical.l"
return(SLASH);
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 256 "lexical.l"
return(STAR);
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 257 "lexical.l"
return(STARSTAR);
	YY_BREAK
case 72:
#line 259 "lexical.l"
case 73:
YY_RULE_SETUP
#line 259 "lexical.l"
return(UPARROW);
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 260 "lexical.l"
return(Sarray);
	YY_BREAK
case 75:
#line 262 "lexical.l"
case 76:
#line 263 "lexical.l"
case 77:
#line 264 "lexical.l"
case 78:
YY_RULE_SETUP
#line 264 "lexical.l"
return(Enum);
	YY_BREAK
case 79:
#line 266 "lexical.l"
case 80:
YY_RULE_SETUP
#line 266 "lexical.l"
return(Sstring);
	YY_BREAK
case 81:
#line 269 "lexical.l"
case 82:
YY_RULE_SETUP
#line 269 "lexical.l"
{
    register int c;
    while ((c = input())){
        if (c == '}')
            break;
        else if (c == '*'){
            if ((c = input()) == ')')
                break;
            else
                unput (c);
        }
        else if (c == '\n')
            line_no++;
        else if (c == 0)
        fprintf (stderr, "Unexpected EOF inside comment at line %d\n",line_no);
     }
    }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 286 "lexical.l"
{register int com;
       while((com=input()))
	{
         if(com=='\n')
       	{
	  fprintf(stderr, "Comment here! at line %d\n",line_no);
 	  line_no++;
 	  break;
	}
	}
      }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 297 "lexical.l"
;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 299 "lexical.l"
;
	YY_BREAK
case 86:
/* rule 86 can match eol */
YY_RULE_SETUP
#line 300 "lexical.l"
line_no++;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 302 "lexical.l"
{fprintf(stderr,"Lexical analyzer error at line %d : %s\n",line_no,yytext);}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 304 "lexical.l"
ECHO;
	YY_BREAK
#line 1588 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 243 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 243 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 242);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 304 "lexical.l"



int main(int argc, char** argv) {
  int i, tok;
  if (argc > 2) {
        printf("ERROR, arguement too much!\n");
    } else if (argc == 2) {
        yyin = fopen(argv[1], "r");
    } else
        yyin = fopen("test.txt", "r");
  printf("输出格式： 类型，行号，token\n");
  for (i = 0; 1==1; i ++) {
    tok = yylex();
    fprintf(stderr, "%d, %d, %s\n", tok,line_no, yytext);
  }
  return(0);
} /* end of main */

int yywrap() {
  fclose(yyin);
  exit(1);
}


